version: '3'

tasks:
  test:
    silent: true
    cmds:
      - go test .

  buf-gen:
    dir: ./application/grpc/protos
    silent: true
    cmds:
      - buf lint
      - buf generate

  dockerd:
    silent: true
    cmds:
      - dockerd-rootless

  docker:
    silent: true
    cmds:
      - docker compose -f infrastructure/docker-compose.yml up -d --build
      - docker compose -f infrastructure/docker-compose.yml logs -f

  clear-docker:
    silent: true
    cmds:
      - docker compose -f infrastructure/docker-compose.yml down -v

  investor-onboard:
    silent: true
    cmds:
      - cmd: |
          grpcurl -protoset <(buf build -o -) -plaintext -d @ localhost:8080 deposits.v1.InvestorsService/Onboard <<EOM
          {
            "investor": {
              "name": "Jane"
            }
          }
          EOM

  deposit-setup:
    silent: true
    cmds:
      - cmd: |
          grpcurl -protoset <(buf build -o -) -plaintext -d @ localhost:8080 deposits.v1.InvestorsService/Onboard <<EOM
          {"name": "Jane"}
          EOM
