version: '3'

tasks:
  test:
    silent: true
    cmds:
      - go test .

  buf-gen:
    dir: ./application/grpc/protos
    silent: true
    cmds:
      - buf lint
      - buf generate

  dockerd:
    silent: true
    cmds:
      - dockerd-rootless

  docker:
    silent: true
    cmds:
      - docker compose -f infrastructure/docker-compose.yml up -d --build
      - docker compose -f infrastructure/docker-compose.yml logs -f

  clear-docker:
    silent: true
    cmds:
      - docker compose -f infrastructure/docker-compose.yml down -v

  investor-onboard:
    silent: true
    cmds:
      - cmd: |
          grpcurl -protoset <(buf build -o -) -plaintext -d @ localhost:8080 deposits.v1.InvestorsService/Onboard <<EOM
          {
            "investor": {
              "name": "Jane"
            }
          }
          EOM

  deposit-create:
    silent: true
    cmds:
      - cmd: |
          grpcurl -protoset <(buf build -o -) -plaintext -d @ localhost:8080 deposits.v1.DepositsService/Create <<EOM
          {
            "investor_id": "{{.CLI_ARGS}}",
            "deposit": {
                "pots": [
                    {
                        "name": "Pot A",
                        "accounts": [
                            {
                                "wrapper_type": 1,
                                "nominal_amount": 10000
                            },
                            {
                                "wrapper_type": 2,
                                "nominal_amount": 20000
                            },
                            {
                                "wrapper_type": 3,
                                "nominal_amount": 50000
                            }
                        ]
                    },
                    {
                        "name": "Pot B",
                        "accounts": [
                            {
                                "wrapper_type": 1,
                                "nominal_amount": 20000
                            }
                        ]
                    }
                ]
            }
          }
          EOM
